<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Snappy" Id="{fab0c229-8c37-418d-9cd2-a63405d9a539}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no_explicit_call' := 'do not call this POU directly'}
FUNCTION_BLOCK FINAL FB_Snappy
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	
	itfISerializer		: I_Serializer := GCL_TcHaxx_Snappy.cDefaultJsonSerializer;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{4cb2ac37-dde9-44ad-953b-fb6cd1ecf35f}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains 	: BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode 	: BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	itfSerializer	: I_Serializer;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Snappy">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Snappy.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>