<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TcTest" Id="{5eaa564f-dc96-42cc-b51b-1a0ce20d2409}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FINAL FB_TcTest
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

TEST('huhu');

TEST_FINISHED_NAMED('hallo');

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>