<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TcUnitAdapter" Id="{9a3e8679-ffe2-40a8-b498-cb88fd65cd9f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FINAL FB_TcUnitAdapter IMPLEMENTS I_TestFrameWorkAdapter
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_TcUnitAdapter">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>