name: CI/CD
on:
  push:
    branches:
        - main
    paths:
      - 'src/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:
  ci-tchaxx-snappy-cli:
    name: CI - TcHaxx.Snappy.CLI
    runs-on: ubuntu-latest
    env:
      solution: ./TcHaxx.Snappy.CLI.sln
      dotnet_versions: |
                        6.0.x
                        8.0.x
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.dotnet_versions}}
      - name: Restore dependencies
        run: dotnet restore ${{ env.solution }}
      - name: Build
        run: dotnet build -c Release --no-restore ${{ env.solution }}
      - name: Test
        if: success()
        run: dotnet test -c Release --no-build --verbosity normal ${{ env.solution }}

  ci-tchaxx-snappy-tc:
    name: CI - TcHaxx.Snappy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Build TcHaxx.Snappy
        uses: Zeugwerk/zkbuild-action@1.0.0
        with:
            username: ${{ secrets.ACTIONS_ZGWK_USERNAME }}
            password: ${{ secrets.ACTIONS_ZGWK_PASSWORD }}
      - name: Upload *.library
        uses: actions/upload-artifact@v4
        with:
            name: snappy
            path: |
              **/*.compiled-library
              **/*.library